### ISSUE TITLE
Excel file missing

### ISSUE THREAD

**Issue by Kraush15** [wri/charm-global-level#1]
### Subject of the issue
The Excel file is missing. Under the data processed folder there is no excel file.

Am I missing something? 

Thank you for your patience and support.

**Comment by loganbyers** [comment]
Hello, thanks for reaching out. We will add more documentation in the README to make this clear, but the data input and output file associated with the initial publication [1] can be accessed through GitHub Releases[2] along with the code used for that publication.

[1] https://doi.org/10.1038/s41586-023-06187-1
[2] https://github.com/wri/charm-global-level/releases/tag/v1.0
